name: 'ethiomed_dbt'
version: '1.0.0'

profile: 'ethiomed_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ethiomed_dbt:
    src:                # for models/src/
      +materialized: view
    staging:            # for models/staging/
      +materialized: view
    marts:              # for models/marts/
      +materialized: table
